set_property SRC_FILE_INFO {cfile:{Z:/ESL projects/project_5/project_5.srcs/constrs_1/new/const1111.xdc} rfile:../../../project_5.srcs/constrs_1/new/const1111.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports led_o]
