set_property SRC_FILE_INFO {cfile:{Z:/ESL projects/project_2/project_2.srcs/constrs_1/new/andrzeju.xdc} rfile:../../../project_2.srcs/constrs_1/new/andrzeju.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports led_o]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports led_o]
